theme: jekyll-theme-slate
title: KernelHaven
description: KernelHaven project web site.
favicon_url: https://avatars2.githubusercontent.com/u/26871806
show_downloads: true
gpl_url: https://jenkins-2.sse.uni-hildesheim.de/job/KH_Releases/lastSuccessfulBuild/artifact/build/KernelHaven_GPLv3.zip
apache_url: https://jenkins-2.sse.uni-hildesheim.de/job/KH_Releases/lastSuccessfulBuild/artifact/build/KernelHaven_Apache-2.0.zip
organization_url: https://github.com/KernelHaven/
department_url: https://sse.uni-hildesheim.de/
company_url: https://www.uni-hildesheim.de/
header_pages:
  - Publications.md
  - Video Tutorials.md